WARNING 2024-11-22 12:10:39,376 log 27996 31680 Not Found: /favicon.ico
WARNING 2024-11-22 12:10:39,376 log 27996 31680 Not Found: /favicon.ico
WARNING 2024-11-22 12:10:39,377 basehttp 27996 31680 "GET /favicon.ico HTTP/1.1" 404 2449
WARNING 2024-11-22 12:10:39,377 basehttp 27996 31680 "GET /favicon.ico HTTP/1.1" 404 2449
WARNING 2024-11-22 12:11:40,580 log 27996 31680 Not Found: /mvn/123
WARNING 2024-11-22 12:11:40,580 log 27996 31680 Not Found: /mvn/123
WARNING 2024-11-22 12:11:40,581 basehttp 27996 31680 "GET /mvn/123 HTTP/1.1" 404 2437
WARNING 2024-11-22 12:11:40,581 basehttp 27996 31680 "GET /mvn/123 HTTP/1.1" 404 2437
WARNING 2024-11-22 12:16:44,969 log 3344 28432 Not Found: /mvn/123
WARNING 2024-11-22 12:16:44,969 log 3344 28432 Not Found: /mvn/123
WARNING 2024-11-22 12:16:44,978 basehttp 3344 28432 "GET /mvn/123 HTTP/1.1" 404 2437
WARNING 2024-11-22 12:16:44,978 basehttp 3344 28432 "GET /mvn/123 HTTP/1.1" 404 2437
WARNING 2024-11-22 12:20:27,200 log 13356 4408 Not Found: /mvn/123
WARNING 2024-11-22 12:20:27,200 log 13356 4408 Not Found: /mvn/123
WARNING 2024-11-22 12:20:27,200 basehttp 13356 4408 "GET /mvn/123 HTTP/1.1" 404 2437
WARNING 2024-11-22 12:20:27,200 basehttp 13356 4408 "GET /mvn/123 HTTP/1.1" 404 2437
WARNING 2024-11-22 12:20:28,135 log 13356 4408 Not Found: /mvn/123
WARNING 2024-11-22 12:20:28,135 log 13356 4408 Not Found: /mvn/123
WARNING 2024-11-22 12:20:28,135 basehttp 13356 4408 "GET /mvn/123 HTTP/1.1" 404 2437
WARNING 2024-11-22 12:20:28,135 basehttp 13356 4408 "GET /mvn/123 HTTP/1.1" 404 2437
WARNING 2024-11-22 12:20:53,309 log 13356 4408 Not Found: /mvn/123
WARNING 2024-11-22 12:20:53,309 log 13356 4408 Not Found: /mvn/123
WARNING 2024-11-22 12:20:53,309 basehttp 13356 4408 "GET /mvn/123 HTTP/1.1" 404 2437
WARNING 2024-11-22 12:20:53,309 basehttp 13356 4408 "GET /mvn/123 HTTP/1.1" 404 2437
WARNING 2024-11-22 12:20:54,022 log 13356 4408 Not Found: /mvn/123
WARNING 2024-11-22 12:20:54,022 log 13356 4408 Not Found: /mvn/123
WARNING 2024-11-22 12:20:54,023 basehttp 13356 4408 "GET /mvn/123 HTTP/1.1" 404 2437
WARNING 2024-11-22 12:20:54,023 basehttp 13356 4408 "GET /mvn/123 HTTP/1.1" 404 2437
WARNING 2024-11-22 12:20:54,389 log 13356 4408 Not Found: /mvn/123
WARNING 2024-11-22 12:20:54,389 log 13356 4408 Not Found: /mvn/123
WARNING 2024-11-22 12:20:54,389 basehttp 13356 4408 "GET /mvn/123 HTTP/1.1" 404 2437
WARNING 2024-11-22 12:20:54,389 basehttp 13356 4408 "GET /mvn/123 HTTP/1.1" 404 2437
WARNING 2024-11-22 12:20:54,657 log 13356 4408 Not Found: /mvn/123
WARNING 2024-11-22 12:20:54,657 log 13356 4408 Not Found: /mvn/123
WARNING 2024-11-22 12:20:54,658 basehttp 13356 4408 "GET /mvn/123 HTTP/1.1" 404 2437
WARNING 2024-11-22 12:20:54,658 basehttp 13356 4408 "GET /mvn/123 HTTP/1.1" 404 2437
ERROR 2024-11-22 16:31:35,685 log 33052 33648 Internal Server Error: /mvn/123/
Traceback (most recent call last):
  File "F:\Anaconda\envs\django\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Python-pro\hub.amusi755.com\project\project\views.py", line 47, in mvn
    return render(request, 'box.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: box.html
ERROR 2024-11-22 16:31:35,685 log 33052 33648 Internal Server Error: /mvn/123/
Traceback (most recent call last):
  File "F:\Anaconda\envs\django\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Python-pro\hub.amusi755.com\project\project\views.py", line 47, in mvn
    return render(request, 'box.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: box.html
ERROR 2024-11-22 16:31:35,688 basehttp 33052 33648 "GET /mvn/123/ HTTP/1.1" 500 89762
ERROR 2024-11-22 16:31:35,688 basehttp 33052 33648 "GET /mvn/123/ HTTP/1.1" 500 89762
ERROR 2024-11-22 16:31:37,129 log 33052 33648 Internal Server Error: /mvn/123/
Traceback (most recent call last):
  File "F:\Anaconda\envs\django\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Python-pro\hub.amusi755.com\project\project\views.py", line 47, in mvn
    return render(request, 'box.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: box.html
ERROR 2024-11-22 16:31:37,129 log 33052 33648 Internal Server Error: /mvn/123/
Traceback (most recent call last):
  File "F:\Anaconda\envs\django\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Python-pro\hub.amusi755.com\project\project\views.py", line 47, in mvn
    return render(request, 'box.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: box.html
ERROR 2024-11-22 16:31:37,132 basehttp 33052 33648 "GET /mvn/123/ HTTP/1.1" 500 89762
ERROR 2024-11-22 16:31:37,132 basehttp 33052 33648 "GET /mvn/123/ HTTP/1.1" 500 89762
ERROR 2024-11-22 16:33:27,076 log 33464 10852 Internal Server Error: /mvn/123/
Traceback (most recent call last):
  File "F:\Anaconda\envs\django\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Python-pro\hub.amusi755.com\project\project\views.py", line 47, in mvn
    return render(request, 'project.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: project.html
ERROR 2024-11-22 16:33:27,076 log 33464 10852 Internal Server Error: /mvn/123/
Traceback (most recent call last):
  File "F:\Anaconda\envs\django\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Python-pro\hub.amusi755.com\project\project\views.py", line 47, in mvn
    return render(request, 'project.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: project.html
ERROR 2024-11-22 16:33:27,080 basehttp 33464 10852 "GET /mvn/123/ HTTP/1.1" 500 89828
ERROR 2024-11-22 16:33:27,080 basehttp 33464 10852 "GET /mvn/123/ HTTP/1.1" 500 89828
ERROR 2024-11-22 16:33:29,529 log 33464 10852 Internal Server Error: /mvn/123/
Traceback (most recent call last):
  File "F:\Anaconda\envs\django\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Python-pro\hub.amusi755.com\project\project\views.py", line 47, in mvn
    return render(request, 'project.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: project.html
ERROR 2024-11-22 16:33:29,529 log 33464 10852 Internal Server Error: /mvn/123/
Traceback (most recent call last):
  File "F:\Anaconda\envs\django\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Python-pro\hub.amusi755.com\project\project\views.py", line 47, in mvn
    return render(request, 'project.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: project.html
ERROR 2024-11-22 16:33:29,534 basehttp 33464 10852 "GET /mvn/123/ HTTP/1.1" 500 89828
ERROR 2024-11-22 16:33:29,534 basehttp 33464 10852 "GET /mvn/123/ HTTP/1.1" 500 89828
ERROR 2024-11-22 16:33:44,971 log 33584 30528 Internal Server Error: /mvn/123/
Traceback (most recent call last):
  File "F:\Anaconda\envs\django\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Python-pro\hub.amusi755.com\project\project\views.py", line 47, in mvn
    return render(request, 'project/box.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: project/box.html
ERROR 2024-11-22 16:33:44,971 log 33584 30528 Internal Server Error: /mvn/123/
Traceback (most recent call last):
  File "F:\Anaconda\envs\django\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Python-pro\hub.amusi755.com\project\project\views.py", line 47, in mvn
    return render(request, 'project/box.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: project/box.html
ERROR 2024-11-22 16:33:44,975 basehttp 33584 30528 "GET /mvn/123/ HTTP/1.1" 500 89892
ERROR 2024-11-22 16:33:44,975 basehttp 33584 30528 "GET /mvn/123/ HTTP/1.1" 500 89892
ERROR 2024-11-22 16:33:46,042 log 33584 30528 Internal Server Error: /mvn/123/
Traceback (most recent call last):
  File "F:\Anaconda\envs\django\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Python-pro\hub.amusi755.com\project\project\views.py", line 47, in mvn
    return render(request, 'project/box.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: project/box.html
ERROR 2024-11-22 16:33:46,042 log 33584 30528 Internal Server Error: /mvn/123/
Traceback (most recent call last):
  File "F:\Anaconda\envs\django\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Python-pro\hub.amusi755.com\project\project\views.py", line 47, in mvn
    return render(request, 'project/box.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: project/box.html
ERROR 2024-11-22 16:33:46,045 basehttp 33584 30528 "GET /mvn/123/ HTTP/1.1" 500 89892
ERROR 2024-11-22 16:33:46,045 basehttp 33584 30528 "GET /mvn/123/ HTTP/1.1" 500 89892
ERROR 2024-11-22 16:40:30,637 log 30164 29412 Internal Server Error: /mvn/123/
Traceback (most recent call last):
  File "F:\Anaconda\envs\django\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Python-pro\hub.amusi755.com\project\project\views.py", line 47, in mvn
    return render(request, 'project/box.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: project/box.html
ERROR 2024-11-22 16:40:30,637 log 30164 29412 Internal Server Error: /mvn/123/
Traceback (most recent call last):
  File "F:\Anaconda\envs\django\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Python-pro\hub.amusi755.com\project\project\views.py", line 47, in mvn
    return render(request, 'project/box.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: project/box.html
ERROR 2024-11-22 16:40:30,641 basehttp 30164 29412 "GET /mvn/123/ HTTP/1.1" 500 89892
ERROR 2024-11-22 16:40:30,641 basehttp 30164 29412 "GET /mvn/123/ HTTP/1.1" 500 89892
ERROR 2024-11-22 16:40:58,698 log 30164 29412 Internal Server Error: /mvn/123/
Traceback (most recent call last):
  File "F:\Anaconda\envs\django\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Python-pro\hub.amusi755.com\project\project\views.py", line 47, in mvn
    return render(request, 'project/box.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: project/box.html
ERROR 2024-11-22 16:40:58,698 log 30164 29412 Internal Server Error: /mvn/123/
Traceback (most recent call last):
  File "F:\Anaconda\envs\django\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Python-pro\hub.amusi755.com\project\project\views.py", line 47, in mvn
    return render(request, 'project/box.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: project/box.html
ERROR 2024-11-22 16:40:58,702 basehttp 30164 29412 "GET /mvn/123/ HTTP/1.1" 500 89503
ERROR 2024-11-22 16:40:58,702 basehttp 30164 29412 "GET /mvn/123/ HTTP/1.1" 500 89503
ERROR 2024-11-22 16:42:43,685 log 34412 33856 Internal Server Error: /mvn/123/
Traceback (most recent call last):
  File "F:\Anaconda\envs\django\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Python-pro\hub.amusi755.com\project\project\views.py", line 47, in mvn
    return render(request, 'project/box.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: project/box.html
ERROR 2024-11-22 16:42:43,685 log 34412 33856 Internal Server Error: /mvn/123/
Traceback (most recent call last):
  File "F:\Anaconda\envs\django\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Python-pro\hub.amusi755.com\project\project\views.py", line 47, in mvn
    return render(request, 'project/box.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: project/box.html
ERROR 2024-11-22 16:42:43,689 basehttp 34412 33856 "GET /mvn/123/ HTTP/1.1" 500 90252
ERROR 2024-11-22 16:42:43,689 basehttp 34412 33856 "GET /mvn/123/ HTTP/1.1" 500 90252
ERROR 2024-11-22 16:44:01,479 log 33072 34464 Internal Server Error: /mvn/123/
Traceback (most recent call last):
  File "F:\Anaconda\envs\django\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Python-pro\hub.amusi755.com\project\project\views.py", line 47, in mvn
    return render(request, 'project/box.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: project/box.html
ERROR 2024-11-22 16:44:01,479 log 33072 34464 Internal Server Error: /mvn/123/
Traceback (most recent call last):
  File "F:\Anaconda\envs\django\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Python-pro\hub.amusi755.com\project\project\views.py", line 47, in mvn
    return render(request, 'project/box.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: project/box.html
ERROR 2024-11-22 16:44:01,483 basehttp 33072 34464 "GET /mvn/123/ HTTP/1.1" 500 90250
ERROR 2024-11-22 16:44:01,483 basehttp 33072 34464 "GET /mvn/123/ HTTP/1.1" 500 90250
ERROR 2024-11-22 16:44:30,591 log 23260 8548 Internal Server Error: /mvn/123/
Traceback (most recent call last):
  File "F:\Anaconda\envs\django\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Python-pro\hub.amusi755.com\project\project\views.py", line 47, in mvn
    return render(request, 'project/index.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: project/bindexox.html
ERROR 2024-11-22 16:44:30,591 log 23260 8548 Internal Server Error: /mvn/123/
Traceback (most recent call last):
  File "F:\Anaconda\envs\django\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Python-pro\hub.amusi755.com\project\project\views.py", line 47, in mvn
    return render(request, 'project/index.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: project/bindexox.html
ERROR 2024-11-22 16:44:30,596 basehttp 23260 8548 "GET /mvn/123/ HTTP/1.1" 500 89966
ERROR 2024-11-22 16:44:30,596 basehttp 23260 8548 "GET /mvn/123/ HTTP/1.1" 500 89966
ERROR 2024-11-22 16:44:31,435 log 23260 8548 Internal Server Error: /mvn/123/
Traceback (most recent call last):
  File "F:\Anaconda\envs\django\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Python-pro\hub.amusi755.com\project\project\views.py", line 47, in mvn
    return render(request, 'project/index.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: project/bindexox.html
ERROR 2024-11-22 16:44:31,435 log 23260 8548 Internal Server Error: /mvn/123/
Traceback (most recent call last):
  File "F:\Anaconda\envs\django\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Python-pro\hub.amusi755.com\project\project\views.py", line 47, in mvn
    return render(request, 'project/index.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: project/bindexox.html
ERROR 2024-11-22 16:44:31,438 basehttp 23260 8548 "GET /mvn/123/ HTTP/1.1" 500 89966
ERROR 2024-11-22 16:44:31,438 basehttp 23260 8548 "GET /mvn/123/ HTTP/1.1" 500 89966
ERROR 2024-11-22 16:44:32,697 log 23260 8548 Internal Server Error: /mvn/123/
Traceback (most recent call last):
  File "F:\Anaconda\envs\django\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Python-pro\hub.amusi755.com\project\project\views.py", line 47, in mvn
    return render(request, 'project/index.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: project/bindexox.html
ERROR 2024-11-22 16:44:32,697 log 23260 8548 Internal Server Error: /mvn/123/
Traceback (most recent call last):
  File "F:\Anaconda\envs\django\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Python-pro\hub.amusi755.com\project\project\views.py", line 47, in mvn
    return render(request, 'project/index.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: project/bindexox.html
ERROR 2024-11-22 16:44:32,700 basehttp 23260 8548 "GET /mvn/123/ HTTP/1.1" 500 89966
ERROR 2024-11-22 16:44:32,700 basehttp 23260 8548 "GET /mvn/123/ HTTP/1.1" 500 89966
ERROR 2024-11-22 16:44:47,804 log 33340 34012 Internal Server Error: /mvn/123/
Traceback (most recent call last):
  File "F:\Anaconda\envs\django\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Python-pro\hub.amusi755.com\project\project\views.py", line 47, in mvn
    return render(request, 'project/index.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: project/index.html
ERROR 2024-11-22 16:44:47,804 log 33340 34012 Internal Server Error: /mvn/123/
Traceback (most recent call last):
  File "F:\Anaconda\envs\django\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Python-pro\hub.amusi755.com\project\project\views.py", line 47, in mvn
    return render(request, 'project/index.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: project/index.html
ERROR 2024-11-22 16:44:47,808 basehttp 33340 34012 "GET /mvn/123/ HTTP/1.1" 500 89924
ERROR 2024-11-22 16:44:47,808 basehttp 33340 34012 "GET /mvn/123/ HTTP/1.1" 500 89924
ERROR 2024-11-22 16:44:49,454 log 33340 34012 Internal Server Error: /mvn/123/
Traceback (most recent call last):
  File "F:\Anaconda\envs\django\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Python-pro\hub.amusi755.com\project\project\views.py", line 47, in mvn
    return render(request, 'project/index.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: project/index.html
ERROR 2024-11-22 16:44:49,454 log 33340 34012 Internal Server Error: /mvn/123/
Traceback (most recent call last):
  File "F:\Anaconda\envs\django\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Python-pro\hub.amusi755.com\project\project\views.py", line 47, in mvn
    return render(request, 'project/index.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: project/index.html
ERROR 2024-11-22 16:44:49,457 basehttp 33340 34012 "GET /mvn/123/ HTTP/1.1" 500 89924
ERROR 2024-11-22 16:44:49,457 basehttp 33340 34012 "GET /mvn/123/ HTTP/1.1" 500 89924
ERROR 2024-11-22 16:44:50,182 log 33340 34012 Internal Server Error: /mvn/123/
Traceback (most recent call last):
  File "F:\Anaconda\envs\django\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Python-pro\hub.amusi755.com\project\project\views.py", line 47, in mvn
    return render(request, 'project/index.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: project/index.html
ERROR 2024-11-22 16:44:50,182 log 33340 34012 Internal Server Error: /mvn/123/
Traceback (most recent call last):
  File "F:\Anaconda\envs\django\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Python-pro\hub.amusi755.com\project\project\views.py", line 47, in mvn
    return render(request, 'project/index.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: project/index.html
ERROR 2024-11-22 16:44:50,185 basehttp 33340 34012 "GET /mvn/123/ HTTP/1.1" 500 89924
ERROR 2024-11-22 16:44:50,185 basehttp 33340 34012 "GET /mvn/123/ HTTP/1.1" 500 89924
ERROR 2024-11-22 16:47:57,288 log 18136 26068 Internal Server Error: /mvn/123/
Traceback (most recent call last):
  File "F:\Anaconda\envs\django\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Python-pro\hub.amusi755.com\project\project\views.py", line 37, in mvn
    print(f"Template path: {os.path.join(settings.BASE_DIR, 'project', 'templates', 'project')}")
                            ^^
NameError: name 'os' is not defined. Did you forget to import 'os'
ERROR 2024-11-22 16:47:57,288 log 18136 26068 Internal Server Error: /mvn/123/
Traceback (most recent call last):
  File "F:\Anaconda\envs\django\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Python-pro\hub.amusi755.com\project\project\views.py", line 37, in mvn
    print(f"Template path: {os.path.join(settings.BASE_DIR, 'project', 'templates', 'project')}")
                            ^^
NameError: name 'os' is not defined. Did you forget to import 'os'
ERROR 2024-11-22 16:47:57,291 basehttp 18136 26068 "GET /mvn/123/ HTTP/1.1" 500 76258
ERROR 2024-11-22 16:47:57,291 basehttp 18136 26068 "GET /mvn/123/ HTTP/1.1" 500 76258
ERROR 2024-11-22 16:48:11,724 log 34812 34624 Internal Server Error: /mvn/123/
Traceback (most recent call last):
  File "F:\Anaconda\envs\django\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Python-pro\hub.amusi755.com\project\project\views.py", line 48, in mvn
    return render(request, 'project/index.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: project/index.html
ERROR 2024-11-22 16:48:11,724 log 34812 34624 Internal Server Error: /mvn/123/
Traceback (most recent call last):
  File "F:\Anaconda\envs\django\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Python-pro\hub.amusi755.com\project\project\views.py", line 48, in mvn
    return render(request, 'project/index.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: project/index.html
ERROR 2024-11-22 16:48:11,727 basehttp 34812 34624 "GET /mvn/123/ HTTP/1.1" 500 89924
ERROR 2024-11-22 16:48:11,727 basehttp 34812 34624 "GET /mvn/123/ HTTP/1.1" 500 89924
ERROR 2024-11-22 16:48:54,076 log 21816 29168 Internal Server Error: /mvn/123/
Traceback (most recent call last):
  File "F:\Anaconda\envs\django\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Python-pro\hub.amusi755.com\project\project\views.py", line 48, in mvn
    return render(request, 'project/index.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: project/index.html
ERROR 2024-11-22 16:48:54,076 log 21816 29168 Internal Server Error: /mvn/123/
Traceback (most recent call last):
  File "F:\Anaconda\envs\django\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Python-pro\hub.amusi755.com\project\project\views.py", line 48, in mvn
    return render(request, 'project/index.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: project/index.html
ERROR 2024-11-22 16:48:54,079 basehttp 21816 29168 "GET /mvn/123/ HTTP/1.1" 500 89924
ERROR 2024-11-22 16:48:54,079 basehttp 21816 29168 "GET /mvn/123/ HTTP/1.1" 500 89924
ERROR 2024-11-22 16:48:55,008 log 21816 29168 Internal Server Error: /mvn/123/
Traceback (most recent call last):
  File "F:\Anaconda\envs\django\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Python-pro\hub.amusi755.com\project\project\views.py", line 48, in mvn
    return render(request, 'project/index.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: project/index.html
ERROR 2024-11-22 16:48:55,008 log 21816 29168 Internal Server Error: /mvn/123/
Traceback (most recent call last):
  File "F:\Anaconda\envs\django\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Python-pro\hub.amusi755.com\project\project\views.py", line 48, in mvn
    return render(request, 'project/index.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: project/index.html
ERROR 2024-11-22 16:48:55,012 basehttp 21816 29168 "GET /mvn/123/ HTTP/1.1" 500 89924
ERROR 2024-11-22 16:48:55,012 basehttp 21816 29168 "GET /mvn/123/ HTTP/1.1" 500 89924
ERROR 2024-11-22 16:48:55,861 log 21816 29168 Internal Server Error: /mvn/123/
Traceback (most recent call last):
  File "F:\Anaconda\envs\django\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Python-pro\hub.amusi755.com\project\project\views.py", line 48, in mvn
    return render(request, 'project/index.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: project/index.html
ERROR 2024-11-22 16:48:55,861 log 21816 29168 Internal Server Error: /mvn/123/
Traceback (most recent call last):
  File "F:\Anaconda\envs\django\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Python-pro\hub.amusi755.com\project\project\views.py", line 48, in mvn
    return render(request, 'project/index.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: project/index.html
ERROR 2024-11-22 16:48:55,864 basehttp 21816 29168 "GET /mvn/123/ HTTP/1.1" 500 89924
ERROR 2024-11-22 16:48:55,864 basehttp 21816 29168 "GET /mvn/123/ HTTP/1.1" 500 89924
ERROR 2024-11-22 16:48:56,343 log 21816 29168 Internal Server Error: /mvn/123/
Traceback (most recent call last):
  File "F:\Anaconda\envs\django\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Python-pro\hub.amusi755.com\project\project\views.py", line 48, in mvn
    return render(request, 'project/index.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: project/index.html
ERROR 2024-11-22 16:48:56,343 log 21816 29168 Internal Server Error: /mvn/123/
Traceback (most recent call last):
  File "F:\Anaconda\envs\django\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Python-pro\hub.amusi755.com\project\project\views.py", line 48, in mvn
    return render(request, 'project/index.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: project/index.html
ERROR 2024-11-22 16:48:56,345 basehttp 21816 29168 "GET /mvn/123/ HTTP/1.1" 500 89924
ERROR 2024-11-22 16:48:56,345 basehttp 21816 29168 "GET /mvn/123/ HTTP/1.1" 500 89924
ERROR 2024-11-22 16:48:56,945 log 21816 29168 Internal Server Error: /mvn/123/
Traceback (most recent call last):
  File "F:\Anaconda\envs\django\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Python-pro\hub.amusi755.com\project\project\views.py", line 48, in mvn
    return render(request, 'project/index.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: project/index.html
ERROR 2024-11-22 16:48:56,945 log 21816 29168 Internal Server Error: /mvn/123/
Traceback (most recent call last):
  File "F:\Anaconda\envs\django\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Python-pro\hub.amusi755.com\project\project\views.py", line 48, in mvn
    return render(request, 'project/index.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: project/index.html
ERROR 2024-11-22 16:48:56,948 basehttp 21816 29168 "GET /mvn/123/ HTTP/1.1" 500 89924
ERROR 2024-11-22 16:48:56,948 basehttp 21816 29168 "GET /mvn/123/ HTTP/1.1" 500 89924
ERROR 2024-11-22 16:48:57,587 log 21816 29168 Internal Server Error: /mvn/123/
Traceback (most recent call last):
  File "F:\Anaconda\envs\django\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Python-pro\hub.amusi755.com\project\project\views.py", line 48, in mvn
    return render(request, 'project/index.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: project/index.html
ERROR 2024-11-22 16:48:57,587 log 21816 29168 Internal Server Error: /mvn/123/
Traceback (most recent call last):
  File "F:\Anaconda\envs\django\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Python-pro\hub.amusi755.com\project\project\views.py", line 48, in mvn
    return render(request, 'project/index.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: project/index.html
ERROR 2024-11-22 16:48:57,590 basehttp 21816 29168 "GET /mvn/123/ HTTP/1.1" 500 89924
ERROR 2024-11-22 16:48:57,590 basehttp 21816 29168 "GET /mvn/123/ HTTP/1.1" 500 89924
ERROR 2024-11-22 16:50:42,644 log 32300 33356 Internal Server Error: /vnbase/
Traceback (most recent call last):
  File "F:\Anaconda\envs\django\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Python-pro\hub.amusi755.com\project\vnbase\views.py", line 6, in index
    return render(request, "index.html")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: index.html
ERROR 2024-11-22 16:50:42,644 log 32300 33356 Internal Server Error: /vnbase/
Traceback (most recent call last):
  File "F:\Anaconda\envs\django\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Python-pro\hub.amusi755.com\project\vnbase\views.py", line 6, in index
    return render(request, "index.html")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: index.html
ERROR 2024-11-22 16:50:42,649 basehttp 32300 33356 "GET /vnbase/ HTTP/1.1" 500 89857
ERROR 2024-11-22 16:50:42,649 basehttp 32300 33356 "GET /vnbase/ HTTP/1.1" 500 89857
ERROR 2024-11-22 17:03:44,117 log 27804 34436 Internal Server Error: /vnbase/mvn/123/
Traceback (most recent call last):
  File "F:\Anaconda\envs\django\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Python-pro\hub.amusi755.com\project\vnbase\views.py", line 30, in mvn
    return render(request, 'project/error.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: project/error.html
ERROR 2024-11-22 17:03:44,117 log 27804 34436 Internal Server Error: /vnbase/mvn/123/
Traceback (most recent call last):
  File "F:\Anaconda\envs\django\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Python-pro\hub.amusi755.com\project\vnbase\views.py", line 30, in mvn
    return render(request, 'project/error.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: project/error.html
ERROR 2024-11-22 17:03:44,121 basehttp 27804 34436 "GET /vnbase/mvn/123/ HTTP/1.1" 500 89962
ERROR 2024-11-22 17:03:44,121 basehttp 27804 34436 "GET /vnbase/mvn/123/ HTTP/1.1" 500 89962
ERROR 2024-11-22 17:19:18,154 log 5516 23116 Internal Server Error: /vnbase/mvn/475472da-7057-420e-baad-2ac64e0b93c4/
Traceback (most recent call last):
  File "F:\Anaconda\envs\django\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Python-pro\hub.amusi755.com\project\vnbase\views.py", line 33, in mvn
    return render(request, f"vnbase/box{vpn_link.level}.html", context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\template\base.py", line 196, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\template\base.py", line 481, in parse
    raise self.error(token, e)
  File "F:\Anaconda\envs\django\Lib\site-packages\django\template\base.py", line 479, in parse
    filter_expression = self.compile_filter(token.contents)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\template\base.py", line 597, in compile_filter
    return FilterExpression(token, self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\template\base.py", line 698, in __init__
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '$date_name_daoqi' from '$date_name_daoqi'
ERROR 2024-11-22 17:19:18,154 log 5516 23116 Internal Server Error: /vnbase/mvn/475472da-7057-420e-baad-2ac64e0b93c4/
Traceback (most recent call last):
  File "F:\Anaconda\envs\django\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Python-pro\hub.amusi755.com\project\vnbase\views.py", line 33, in mvn
    return render(request, f"vnbase/box{vpn_link.level}.html", context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\template\base.py", line 196, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\template\base.py", line 481, in parse
    raise self.error(token, e)
  File "F:\Anaconda\envs\django\Lib\site-packages\django\template\base.py", line 479, in parse
    filter_expression = self.compile_filter(token.contents)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\template\base.py", line 597, in compile_filter
    return FilterExpression(token, self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Anaconda\envs\django\Lib\site-packages\django\template\base.py", line 698, in __init__
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '$date_name_daoqi' from '$date_name_daoqi'
ERROR 2024-11-22 17:19:18,161 basehttp 5516 23116 "GET /vnbase/mvn/475472da-7057-420e-baad-2ac64e0b93c4/ HTTP/1.1" 500 164191
ERROR 2024-11-22 17:19:18,161 basehttp 5516 23116 "GET /vnbase/mvn/475472da-7057-420e-baad-2ac64e0b93c4/ HTTP/1.1" 500 164191
